### ISSUE TITLE
Some Channel Can't Work 

### ISSUE THREAD

**Issue by chenyucheng0503** [zefr0x/python-telegram2rss#2]
Some channel can't be fount in https://t.me/s/channel_id, so can't be parse correctly. Can you fix it?

**Comment by zefr0x** [comment]
Those channels are not exposed in telegram's web interface, then there is no way to access them other then using the official API.

I don't know why telegram don't exposed some public channels in the web interface (are they private? did the admin disabled it?), but I couldn't find a way around it.

**Comment by chenyucheng0503** [comment]
Thanks, it seems that no way to get them using offical API. So I use telethon to get those messages and generate RSS content. 
Here is the repository: 
[https://github.com/chenyucheng0503/tgtorss](https://github.com/chenyucheng0503/tgtorss)
